# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dealol' do
  use_frameworks!

  target 'DealolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DealolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
